feat: add options to the add function and SSH config file support
- Add a new option `--username` to the `add` function
- Add a new option `--port` to the `add` function
- Add a new option `--key` to the `add` function
- Add logic to add the host to the SSH config file if requested

diff --git a/.func/cli/hos b/.func/cli/hos
--- a/.func/cli/hos
+++ b/.func/cli/hos
@@ -16,8 +16,11 @@ select_all() {
 }
 
 # @cmd Add a hostname to the list
-# @option --name   Name of the host
-# @option --ip     IP address of the host
+# @option --name       Name of the host
+# @option --ip         IP address of the host
+# @option --username   Username to use
+# @option --port       Port to use
+# @option --key        Key to use / IdentityFile
 add() {
     if [ -z $argc_name ]; then
         name=$(gum input --placeholder "Name?")
@@ -48,7 +51,44 @@ add() {
     if gum confirm "are you sure you want to add $new_object"; then
         echo $new_object | doas tee -a $hostnames
     fi
-    gum log --structured --level info "added $new_object"
+    gum log --structured --level info "added $new_object to $hostnames"
+
+    if gum confirm "do you want to add $name to $sshfile too"; then
+        if grep -q "Host $name" $sshfile; then
+            gum log --structured --level info "Host $name already exists in $sshfile"
+            continue
+        fi
+
+        string="\n\nHost $name\n\t# $ip\n\thostname $name\n"
+        if [ -z $argc_username ]; then
+            if gum confirm "use current user"; then
+                username=$(whoami)
+            else
+                username=$(gum input --placeholder "Username?")
+            fi
+        else
+            username=$argc_username
+        fi
+        string+="\tuser $username\n"
+        
+        if [ -z $argc_port ]; then
+            port=22
+        else
+            port=$argc_port
+        fi
+        string+="\tport $port\n"
+
+        if [ ! -z $argc_key ]; then
+            string+="\tidentityFile $argc_key\n"
+        elif gum confirm "do you want to add a key for $name"; then
+            key=$(gum input --placeholder "Key?")
+            [ ! -f $key ] && { gum log --structured --level error "Key not found"; exit 1; }
+            string+="\tidentityFile $key\n"
+        fi
+
+        echo -e $string | doas tee -a $sshfile
+    fi
+
     # echo "added successfully"
     exit 0
 }
@@ -97,19 +137,17 @@ remove() {
 }
 
 # @cmd SSH into a hostname
-# @option --hostname   Name of the host
+# @option --name       Name of the host
 # @option --ip         IP address of the host
 # @option --username   Username to use
 # @option --port       Port to use
 # @option --key        Key to use / IdentityFile
-# @arg num[=one|all]
 ssh() {
-    keytrigger=true
     if [ $argc_num == "all" ]; then
         selected=$(select_all)
         keytrigger=false
-    elif [ ! -z $argc_hostname ] && [ ! -z $argc_ip ]; then
-        selected="$argc_ip $argc_hostname"
+    elif [ ! -z $argc_name ] && [ ! -z $argc_ip ]; then
+        selected="$argc_ip $argc_name"
     else
         selected=$(select_many)
     fi
